dir: "CC-AlignBench" # path to the data directory
csv_file: "data.csv"
bg_file: "background.json"
surrounings_type: "simple" #simple, detail
man_token: "<new1> man"
woman_token: "<new2> woman"
index_list: null # list or null
debug: true

OPTION:
  output_dir_path: "./gen_output/01_CustomDiffusion/output"
  delta_ckpt_path_man: "./gen_output/01_CustomDiffusion/logs/man_1/delta-3000.bin"
  delta_ckpt_path_woman: "./gen_output/01_CustomDiffusion/logs/woman_1/delta-3000.bin"
  delta_ckpt_fused: "./gen_output/01_CustomDiffusion/optimized_logs/optimized_man_1+woman_1/delta.bin"

