dir: "CC-AlignBench" # path to the data directory
csv_file: "cc-alignbench-data.csv"
man_token: "sks man"
woman_token: "t@y woman"
index_list: null # list or null

OPTION:
  neg_prompt: "noisy, blurry, soft, deformed, ugly"
  output_dir_path: "./gen_output/06_DreamBooth/output" 
  model_path: "./gen_output/06_DreamBooth/models"
