dir: "CC-AlignBench" # path to the data directory
csv_file: "data.csv"
bg_file: "background.json"
surrounings_type: "simple" #simple, detail
man_token: "sks man"
woman_token: "t@y woman"
index_list: null # list or null
debug: true

OPTION:
  neg_prompt: "noisy, blurry, soft, deformed, ugly"
  output_dir_path: "./gen_output/06_DreamBooth/output" 
  model_path: "./gen_output/06_DreamBooth/models"
